[package]
name = "derec-library"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
derec-cryptography = { path = "../cryptography" }
prost = "0.12"
prost-types = "0.12"
rand = "0.8.5"
sha2 = "0.10.9"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"

[build-dependencies]
prost-build = "0.12"
